  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://43.139.8.195:3306/xiaoyao?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: abcswhu2021
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 43.139.8.195
    port: 6379
    password: abcswhu2021
    lettuce:
      cluster:
        refresh:
          adaptive: true
          period: 20
      pool:
        max-idle: 30
        min-idle: 10
        max-active: 30
        max-wait: 10000
